<?php

declare(strict_types=1);

use Capell\Address\Tests\AddressTestCase;
use Capell\Analytics\Tests\AnalyticsTestCase;
use Capell\Assistant\Tests\AssistantTestCase;
use Capell\Blog\Tests\BlogTestCase;
use Capell\Campaigns\Tests\CampaignsTestCase;
use Capell\Deployments\Tests\TestCase as DeploymentsTestCase;
use Capell\DeveloperTools\Tests\DeveloperToolsTestCase;
use Capell\FilamentPeek\Tests\FilamentPeekTestCase;
use Capell\Forms\Tests\FormsTestCase;
use Capell\HtmlMinify\Tests\HtmlMinifyTestCase;
use Capell\Mcp\Tests\TestCase as McpTestCase;
use Capell\MediaCurator\Tests\MediaCuratorTestCase;
use Capell\Migrator\Tests\MigratorTestCase;
use Capell\Mosaic\Tests\MosaicTestCase;
use Capell\Navigation\Tests\NavigationTestCase;
use Capell\Redirects\Tests\RedirectsTestCase;
use Capell\SeoTools\Tests\SeoToolsTestCase;
use Capell\SiteSearch\Tests\SiteSearchTestCase;
use Capell\Tags\Tests\TagsTestCase;
use Capell\Tests\Packages\PackagesTestCase;
use Capell\Tests\Packages\UninstalledPackagesTestCase;
use Capell\ThemeStudio\Admin\Tests\ThemeStudioAdminTestCase;
use Capell\ThemeStudio\Core\Tests\ThemeStudioCoreTestCase;
use Capell\Toolbar\Tests\ToolbarTestCase;
use Capell\WordPressImporter\Tests\WordPressImporterTestCase;
use Capell\Workspaces\Tests\WorkspacesTestCase;

pest()->extend(AddressTestCase::class)->group('address')->in('../packages/address/tests');
pest()->extend(AnalyticsTestCase::class)->group('analytics')->in('../packages/analytics/tests');
pest()->extend(AssistantTestCase::class)->group('assistant')->in('../packages/assistant/tests');
pest()->extend(MigratorTestCase::class)->group('migrator')->in('../packages/migrator/tests');
pest()->extend(PackagesTestCase::class)->group('authentication-log')->in('../packages/authentication-log/tests');
pest()->extend(BlogTestCase::class)->group('blog')->in('../packages/blog/tests');
pest()->extend(CampaignsTestCase::class)->group('campaigns')->in('../packages/campaigns/tests');
pest()->extend(PackagesTestCase::class)->group('content-blocks')->in('../packages/content-blocks/tests');
pest()->extend(PackagesTestCase::class)->group('default-theme')->in('../packages/default-theme/tests');
pest()->extend(DeploymentsTestCase::class)->group('deployments')->in('../packages/deployments/tests');
pest()->extend(DeveloperToolsTestCase::class)->group('developer-tools')->in('../packages/developer-tools/tests');
pest()->extend(FilamentPeekTestCase::class)->group('filament-peek')->in('../packages/filament-peek/tests');
pest()->extend(FormsTestCase::class)->group('forms')->in('../packages/forms/tests');
pest()->extend(HtmlMinifyTestCase::class)->group('html-minify')->in('../packages/html-minify/tests');
pest()->extend(MediaCuratorTestCase::class)->group('media-curator')->in('../packages/media-curator/tests');
pest()->extend(McpTestCase::class)->group('mcp')->in('../packages/mcp/tests');
pest()->extend(MosaicTestCase::class)->group('mosaic')->in('../packages/mosaic/tests');
pest()->extend(NavigationTestCase::class)->group('navigation')->in('../packages/navigation/tests');
pest()->extend(PackagesTestCase::class)->in('Packages');
pest()->extend(UninstalledPackagesTestCase::class)->in('UninstalledPackages');
pest()->extend(RedirectsTestCase::class)->group('redirects')->in('../packages/redirects/tests');
pest()->extend(SeoToolsTestCase::class)->group('seo-tools')->in('../packages/seo-tools/tests');
pest()->extend(SiteSearchTestCase::class)->group('site-search')->in('../packages/site-search/tests');
pest()->extend(TagsTestCase::class)->group('tags')->in('../packages/tags/tests');
pest()->extend(PackagesTestCase::class)->group('theme-agency')->in('../packages/theme-agency/tests');
pest()->extend(PackagesTestCase::class)->group('theme-corporate')->in('../packages/theme-corporate/tests');
pest()->extend(PackagesTestCase::class)->group('theme-saas')->in('../packages/theme-saas/tests');
pest()->extend(ThemeStudioAdminTestCase::class)->group('theme-studio-admin')->in('../packages/theme-studio-admin/tests');
pest()->extend(ThemeStudioCoreTestCase::class)->group('theme-studio-core')->in('../packages/theme-studio-core/tests');
pest()->extend(ToolbarTestCase::class)->group('toolbar')->in('../packages/toolbar/tests');
pest()->extend(WorkspacesTestCase::class)->group('workspaces')->in('../packages/workspaces/tests');
pest()->extend(WordPressImporterTestCase::class)->group('wordpress-importer')->in('../packages/wordpress-importer/tests');
